import {
  DiamondNecklace,
  Diamond2,
  Diamond3,
  Diamond8,
  Diamond7,
  Diamond6,
  Diamond9,
  Diamond10,
  GoldNecklace,
  GoldNecklace2,
  GoldNecklace3,
  GoldNecklace4,
  GoldNecklace5,
  GoldNecklace6,
  GoldNecklace7,
  GoldBangle,
  GoldBangle2,
  GoldBangle3,
  GoldBangle4,
  GoldBangle5,
  GoldBangle6,
  DiamondBangle1,
  DiamondBangle2,
  DiamondBangle3,
  DiamondBracelet1,
  DiamondBracelet2,
  DiamondBracelet3,
  GoldRing1,
  GoldRing2,
  GoldRing3,
  GoldRing4,
  DiamondRing1,
  DiamondRing2,
  DiamondRing3,
  DiamondRing4,
} from "../../Assets";
const products = {
  list1: [
    {
      label: "Diamond Necklace with Green Rubies",
      id: 1,
      amount: 12000,
      quantity: 1,
      description: "18k purity with gross weight of 67 grams",
      image: DiamondNecklace,
    },
    {
      label: "Diamond Necklace with Pure White Diamonds",
      id: 2,
      amount: 7000,
      quantity: 1,
      description: "18k purity with gross weight of 45 grams",
      image: Diamond2,
    },
    {
      label: "Diamond Necklace with a Base of Gold",
      id: 3,
      amount: 18000,
      quantity: 1,
      description: "18k purity with gross weight of 60 grams",
      image: Diamond3,
    },
    {
      label: "Double Layer Diamond Necklace with Green Rubies",
      id: 4,
      amount: 16000,
      quantity: 1,
      description: "18k purity with gross weight of 52 grams",
      image: Diamond8,
    },
    {
      label: "Single layer Diamond Sets with Green Rubies",
      id: 5,
      amount: 8000,
      quantity: 1,
      description: "18k purity with gross weight of 52 grams",
      image: Diamond7,
    },
    {
      label: "Diamond Necklace with Red Rubies and Drop Pattern",
      id: 6,
      amount: 17000,
      quantity: 1,
      description: "18k purity with gross Weight of 60 grams",
      image: Diamond6,
    },
  ],
  list2: [
    {
      label: "Pure Gold Necklace Set",
      id: 7,
      amount: 8000,
      quantity: 1,
      description:
        "22k purity with gross weight of 102 grams and it comes with Matching Earrings",
      image: GoldNecklace,
    },
    {
      label: "Semi Long Gold Necklace Set ",
      id: 8,
      amount: 4000,
      quantity: 1,
      description:
        "22k purity with gross weight of 55 grams and comes with Matching Earrings ",
      image: GoldNecklace2,
    },
    {
      label: "5 layer Dramatic Gold Necklace Set ",
      id: 9,
      amount: 7000,
      quantity: 1,
      description:
        "22k purity with gross weight of 94 grams and comes with Matching Earrings",
      image: GoldNecklace3,
    },
    {
      label: " Antique Gold Choker Set ",
      id: 10,
      amount: 3000,
      quantity: 1,
      description:
        "22k purity with gross weight of 46 grams and with Matching Earrings ",
      image: GoldNecklace4,
    },
    {
      label: "Detailed Choker Gold Necklace Set",
      id: 11,
      amount: 4000,
      quantity: 1,
      description: "22k purity gross weight 57 grams and Matching Earrings ",
      image: GoldNecklace5,
    },
    {
      label: "Gold Necklace with Hexagon  Pendant",
      id: 12,
      amount: 3000,
      quantity: 1,
      description:
        "22k purity with gross weight of 47 grams and Matching Earrings ",
      image: GoldNecklace6,
    },
  ],
  list3: [
    {
      id: 1,
      image: GoldNecklace7,
    },
    {
      id: 2,
      image: GoldNecklace5,
    },
    {
      id: 3,
      image: Diamond9,
    },
    {
      id: 4,
      image: Diamond10,
    },
  ],
  list4: [
    {
      label: "Gold Bangles ",
      id: 1,
      amount: 460,
      quantity: 1,
      description: "22k purity with gross weight of 58 grams ",
      image: GoldBangle,
    },
    {
      label: "Gold Bangles ",
      id: 1,
      amount: 360,
      quantity: 1,
      description: "22k purity with gross weight of 45 grams ",
      image: GoldBangle2,
    },
    {
      label: "Gold Bangles ",
      id: 3,
      amount: 150,
      quantity: 1,
      description: "22k purity with gross weight of 20 grams ",
      image: GoldBangle3,
    },
    {
      label: "Gold Bracelets ",
      id: 4,
      amount: 68,
      quantity: 1,
      description: "18k purity with gross weight of 10 grams ",
      image: GoldBangle4,
    },
    {
      label: "Gold Bracelets ",
      id: 5,
      amount: 540,
      quantity: 1,
      description: "22k purity with gross weight of 65 grams ",
      image: GoldBangle5,
    },
    {
      label: "Gold Bracelets ",
      id: 6,
      amount: 190,
      quantity: 1,
      description: "22k purity with gross weight of 23 grams ",
      image: GoldBangle6,
    },
    {
      label: "Diamond Bangles ",
      id: 7,
      amount: 800,
      quantity: 1,
      description: "18k purity with gross weight of 43 grams ",
      image: DiamondBangle1,
    },
    {
      label: "Diamond Bangles ",
      id: 8,
      amount: 1300,
      quantity: 1,
      description: "18k purity with gross weight of 56 grams ",
      image: DiamondBangle2,
    },
    {
      label: "Diamond Bangles ",
      id: 9,
      amount: 1100,
      quantity: 1,
      description: "18k purity with gross weight of 64 grams ",
      image: DiamondBangle3,
    },
    {
      label: "Diamond Bracelet ",
      id: 10,
      amount: 500,
      quantity: 1,
      description: "18k purity with gross weight of 16 grams ",
      image: DiamondBracelet1,
    },
    {
      label: "Diamond Bracelet ",
      id: 11,
      amount: 900,
      quantity: 1,
      description: "18k purity with gross weight of 37 grams ",
      image: DiamondBracelet2,
    },
    {
      label: "Diamond Bracelet ",
      id: 12,
      amount: 300,
      quantity: 1,
      description: "18k purity with gross weight of 17 grams ",
      image: DiamondBracelet3,
    },
  ],
  list5: [
    {
      label: "Unique Gold Cocktail Ring ",
      id: 1,
      amount: 117,
      quantity: 1,
      description: "18k purity with gross weight of 11 grams ",
      image: GoldRing1,
    },
    {
      label: "Circular Gold Ring with Enamel ",
      id: 2,
      amount: 120,
      quantity: 1,
      description: "18k purity with gross weight of 12 grams ",
      image: GoldRing2,
    },
    {
      label: "Gold Ring with Spiral Pattern",
      id: 3,
      amount: 97,
      quantity: 1,
      description: "22k purity with gross weight of 11 grams ",
      image: GoldRing3,
    },
    {
      label: "Gold Ring with Leaf Pattern ",
      id: 4,
      amount: 98,
      quantity: 1,
      description: "22k purity with gross weight of 12 grams ",
      image: GoldRing4,
    },
    {
      label: "Diamond Ring ",
      id: 5,
      amount: 96,
      quantity: 1,
      description: "18k purity with gross weight of 5 grams ",
      image: DiamondRing1,
    },
    {
      label: "Diamond Ring",
      id: 6,
      amount: 73,
      quantity: 1,
      description: "18k purity with gross weight of 4 grams ",
      image: DiamondRing2,
    },
    {
      label: "Real Diamond Ring ",
      id: 7,
      amount: 240,
      quantity: 1,
      description: "18k purity with gross weight of 12 grams ",
      image: DiamondRing3,
    },
    {
      label: "Real Diamond Ring ",
      id: 4,
      amount: 76,
      quantity: 1,
      description: "18k purity with gross weight of 3 grams ",
      image: DiamondRing4,
    },
  ],
};

export { products };
