import {
  DiamondNecklace,
  Diamond2,
  Diamond3,
  Diamond8,
  Diamond7,
  Diamond6,
  GoldNecklace,
  GoldNecklace2,
  GoldNecklace3,
  GoldNecklace4,
  GoldNecklace5,
  GoldNecklace6,
} from "../../Assests";
const products = {
  list1: [
    {
      label: "Diamond Necklace with Green Rubies",
      id: 1,
      amount: 12000,
      quantity: 1,
      description: "18k purity with gross weight of 67 grams",
      image: DiamondNecklace,
    },
    {
      label: "Diamond Necklace with Pure White Diamonds",
      id: 2,
      amount: 7000,
      quantity: 1,
      description: "18k purity with gross weight of 45 grams",
      image: Diamond2,
    },
    {
      label: "Diamond Necklace with a Base of Gold",
      id: 3,
      amount: 18000,
      quantity: 1,
      description: "18k purity with gross weight of 60 grams",
      image: Diamond3,
    },
    {
      label: "Double Layer Diamond Necklace with Green Rubies",
      id: 4,
      amount: 16000,
      quantity: 1,
      description: "18k purity with gross weight of 52 grams",
      image: Diamond8,
    },
    {
      label: "Single layer Diamond Sets with Green Rubies",
      id: 5,
      amount: 8000,
      quantity: 1,
      description: "18k purity with gross weight of 52 grams",
      image: Diamond7,
    },
    {
      label: "Diamond Necklace with Red Rubies and Drop Pattern",
      id: 6,
      amount: 17000,
      quantity: 1,
      description: "18k purity with gross Weight of 60 grams",
      image: Diamond6,
    },
  ],
  list2: [
    {
      label: "Pure Gold Necklace Set",
      id: 7,
      amount: 8000,
      quantity: 1,
      description:
        "22k purity with gross weight of 102 grams and it comes with Matching Earrings",
      image: GoldNecklace,
    },
    {
      label: "Semi Long Gold Necklace Set ",
      id: 8,
      amount: 4000,
      quantity: 1,
      description:
        "22k purity with gross weight of 55 grams and comes with Matching Earrings ",
      image: GoldNecklace2,
    },
    {
      label: "5 layer Dramatic Gold Necklace Set ",
      id: 9,
      amount: 7000,
      quantity: 1,
      description:
        "22k purity with gross weight of 94 grams and comes with Matching Earrings",
      image: GoldNecklace3,
    },
    {
      label: " Antique Gold Choker Set ",
      id: 10,
      amount: 3000,
      quantity: 1,
      description:
        "22k purity with gross weight of 46 grams and with Matching Earrings ",
      image: GoldNecklace4,
    },
    {
      label: "Detailed Choker Gold Necklace Set",
      id: 11,
      amount: 4000,
      quantity: 1,
      description: "22k purity gross weight 57 grams and Matching Earrings ",
      image: GoldNecklace5,
    },
    {
      label: "Gold Necklace with Hexagon  Pendant",
      id: 12,
      amount: 3000,
      quantity: 1,
      description:
        "22k purity with gross weight of 47 grams and Matching Earrings ",
      image: GoldNecklace6,
    },
    {
      label: "Product 2",
      id: 13,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 14,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 15,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 16,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 17,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 18,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 19,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 20,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
    {
      label: "Product 2",
      id: 21,
      amount: 19000,
      quantity: 1,
      description: "This is product 2",
      image: "",
    },
  ],
};

export { products };
